version: '3'

services:
  mysql:
    hostname: db
    container_name: db
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress

  wordpress:
    image: wordpress:latest
    hostname: wordpress
    container_name: wordpress
    ports:
      - '3000:80'
    depends_on:
      - mysql
    links:
      - mysql
      - phpmyadmin
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    volumes:
      #  - ./themes:/var/www/html/wp-content/themes
      #  - ./plugins:/var/www/html/wp-content/plugins
      - ./wordpress:/var/www/html

  phpmyadmin:
    hostname: pma
    container_name: pma
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - '8080:80'
    volumes:
      - /sessions
